modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="giftfromthegods"
version="${file.jarVersion}"
displayName="Gift From The Gods"
authors="TheEmosewaPixel"
description="A mod that gives players a random item every few seconds."

[[dependencies.giftfromthegods]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.giftfromthegods]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
